# Generated by Django 3.2.7 on 2024-05-01 12:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0002_auto_20240501_1951'),
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=600)),
                ('option_type', models.SmallIntegerField(choices=[(0, 'percentive'), (1, 'absolute')])),
                ('cost', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.SmallIntegerField()),
                ('option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='store.option')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.product')),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, 'Waiting to pay'), (1, 'Pending'), (2, 'In process'), (3, 'Sent'), (4, 'Done')], default=0)),
                ('payment_info', models.CharField(blank=True, max_length=160, null=True)),
                ('receive_time', models.DateTimeField()),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('additional_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='card.additionaloption')),
                ('address_to_send_good', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='address_good', to='account.address')),
                ('address_to_send_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='address_invoice', to='account.address')),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='card.delivery')),
                ('discount', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='store.discount')),
                ('orders', models.ManyToManyField(blank=True, to='card.Order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
